language: java

jdk: openjdk8

script:
    - echo "Hola travis"
    - mvn package
    - ssh-keyscan -H 3.20.248.207 >> ~/.ssh/known_hosts
    - ssh-keyscan -H ec2-3-20-248-207.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts
    - chmod 400 instancia.pem
    - ssh -i instancia.pem ubuntu@3.20.248.207 "rm -rf /var/lib/tomcat8/webapps/Netflix*"
    - scp -i instancia.pem target/*.war ubuntu@3.20.248.207:/var/lib/tomcat8/webapps/Netflix.war